---
- name: Configure Debian networking
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces

- name: Reboot
  shell: sleep 2; systemctl reboot
  # Don't wait for completion
  async: 1
  poll: 0
  ignore_errors: true

- name: Wait for server to come back
  become: no
  wait_for_connection:
    delay: 30
    timeout: 120
