---
- name: debian network configuration
  template:
    backup: no
    dest: /etc/network/interfaces
    src: files/interfaces
  when: "ansible_os_family=='Debian'"

- name: restart machine
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  ignore_errors: true

- name: test
  debug:
    msg: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"

- name: waiting for server to come back
  wait_for:
    host: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
    delay: 30
    connect_timeout: 2
    port: 22
  delegate_to: localhost
  become: false
