---
- import_tasks: packages.yml
  tags: network_management

- name: Check whether IPv6 can be disabled
  stat:
    path: /proc/sys/net/ipv6/conf/default/disable_ipv6
  register: v6support
  changed_when: False

- import_tasks: interfaces.yml
  tags: network_management
