---
- name: Install openvswitch packages
  apt:
    name:
      - openvswitch-switch
      - openvswitch-common
  when: bridges|length > 0

- name: Install ifupdown
  apt:
    name: ifupdown
  when: ansible_pkg_mgr == "apt"
