---
- name: Update repositories cache
  apt:
    update_cache: yes
  changed_when: false
  
- name: install openvswitch packages
  apt:
    name: "{{ item }}"
  with_items:
    - openvswitch-switch
    - openvswitch-common
