---
- name: Update repositories cache
  apt:
    update_cache: yes
  changed_when: false
  when: ansible_pkg_mgr == "apt"

- name: Install openvswitch
  apt:
    name: "{{ item }}"
  with_items:
    - openvswitch-switch
    - openvswitch-common
  when: bridges|length > 0
