---
- name: Reboot firewall
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  ignore_errors: true
  notify: Wait for server to come back online

- name: Wait for server to come back online
  wait_for:
    host: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
    delay: 30
    connect_timeout: 2
    port: 22
  delegate_to: localhost
  become: false
